### ISSUE TITLE
Cannot get Peer-Tweet running

### ISSUE THREAD

**Issue by lapin-b** [lmatteis/peer-tweet#11]
Everything's in the title.
I followed the instructions on installing. I ran

``` bash
npm install
npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild
```

After launching with 2 separate instance of terminal with these commands

``` bash
npm run hot-server
npm run start-hot
```

When I start the second command line, I get this output

```
> PeerTweet@0.1.1 start-hot /home/l4p1n/peer-tweet
> cross-env HOT=1 NODE_ENV=development electron ./

(electron) companyName is now a required option to crashReporter.start
Error opening app
The app provided is not a valid Electron app, please read the docs on how to write one:
https://github.com/atom/electron/tree/v0.36.12/docs

Error: Cannot find module 'electron-debug'

npm ERR! Linux 4.2.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start-hot"
npm ERR! node v4.4.4
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! PeerTweet@0.1.1 start-hot: `cross-env HOT=1 NODE_ENV=development electron ./`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the PeerTweet@0.1.1 start-hot script 'cross-env HOT=1 NODE_ENV=development electron ./'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the PeerTweet package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env HOT=1 NODE_ENV=development electron ./
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs PeerTweet
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls PeerTweet
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/l4p1n/peer-tweet/npm-debug.log
```

And here is the content of /home/l4p1n/peer-tweet/npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'start-hot' ]
2 info using npm@3.8.9
3 info using node@v4.4.4
4 verbose run-script [ 'prestart-hot', 'start-hot', 'poststart-hot' ]
5 info lifecycle PeerTweet@0.1.1~prestart-hot: PeerTweet@0.1.1
6 silly lifecycle PeerTweet@0.1.1~prestart-hot: no script for prestart-hot, continuing
7 info lifecycle PeerTweet@0.1.1~start-hot: PeerTweet@0.1.1
8 verbose lifecycle PeerTweet@0.1.1~start-hot: unsafe-perm in lifecycle true
9 verbose lifecycle PeerTweet@0.1.1~start-hot: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/l4p1n/peer-tweet/node_modules/.bin:/usr/bin:/home/l4p1n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle PeerTweet@0.1.1~start-hot: CWD: /home/l4p1n/peer-tweet
11 silly lifecycle PeerTweet@0.1.1~start-hot: Args: [ '-c', 'cross-env HOT=1 NODE_ENV=development electron ./' ]
12 silly lifecycle PeerTweet@0.1.1~start-hot: Returned: code: 1  signal: null
13 info lifecycle PeerTweet@0.1.1~start-hot: Failed to exec start-hot script
14 verbose stack Error: PeerTweet@0.1.1 start-hot: `cross-env HOT=1 NODE_ENV=development electron ./`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid PeerTweet@0.1.1
16 verbose cwd /home/l4p1n/peer-tweet
17 error Linux 4.2.0-36-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start-hot"
19 error node v4.4.4
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error PeerTweet@0.1.1 start-hot: `cross-env HOT=1 NODE_ENV=development electron ./`
22 error Exit status 1
23 error Failed at the PeerTweet@0.1.1 start-hot script 'cross-env HOT=1 NODE_ENV=development electron ./'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the PeerTweet package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cross-env HOT=1 NODE_ENV=development electron ./
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs PeerTweet
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls PeerTweet
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I guess I have to run `npm install --dev` but I prefer to ask to make sure.

**Comment by lmatteis** [comment]
Did it work with `--dev`? I don't have a linux distro to test this on.

**Comment by lapin-b** [comment]
So. I cloned a fresh copy of the repo, ran

```
npm install --dev
npm install electron-debug
```

Then started the server with `npm run hot-server` and started the client `npm run start-hot`. Until there everything is fine.

I've got another problem with the client saying in the devtools

```
Error: Module version mismatch. Expected 47, got 46.
```

I've got no idea of what going on.

**Comment by lmatteis** [comment]
The problem is that you need to install the native modules: https://github.com/lmatteis/peer-tweet#installing-native-modules

I'm not sure how to do that in linux.

**Comment by lapin-b** [comment]
Everything work. It works better if I read properly the README.md :joy:
